services:
  db:
    image: postgres:15.3
    container_name: chatapp-db
    restart: always
    environment:
      POSTGRES_DB: chatappdb
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: 12345678
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: chatapp-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chatappdb
      SPRING_DATASOURCE_USERNAME: chatuser
      SPRING_DATASOURCE_PASSWORD: 12345678
      HOST_IP: ${HOST_IP}                   # inject Wi-Fi IP dynamically
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build: ./frontend
    container_name: chatapp-frontend
    restart: always
    environment:
      VITE_HOST_IP: ${HOST_IP}   # frontend also knows your LAN IP
      CHOKIDAR_USEPOLLING: "true"  # for hot reload on Windows with WSL
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app          # <-- HOT RELOAD FOR FRONTEND
      - /app/node_modules       # <-- IGNORE LOCAL NODE_MODULES


  pgadmin:
    image: dpage/pgadmin4
    container_name: chatapp-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:
  backend_uploads: